### ISSUE TITLE
[Spike] Dependencies management with maven or graddle. 

### ISSUE THREAD

**Issue by mxdxgx** [echolevel/wulfcode#4]
Investigate the possibility of using maven or graddle.

**Comment by echolevel** [comment]
Cool - I'll need to learn more about them both, but I'll look into it.

**Comment by mxdxgx** [comment]
I just checked with maven, not sure how to manage a dependency plugin (themidibus for processing) thought I successfully manage Processing. I'll check that too.

**Comment by MaximeGir** [comment]
Spike result: 

I think maven might be a good choice, as we're able to add processing through maven repo. 
For midibus, it's not available under maven repo as of right now, but I added it manually in the maven dependencies (midibus would be at the root of the project). 

Another advantage is that maven is generating user classpath file from the pom.xml file.
I'll push my branch (PR) and you guys can check it out and find out how you like / hate it :P 

Graddle seems overkill right now, let me know your thoughts.
